CREATE TABLE inventory_item
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_article BIGINT,
    quantity        INTEGER                                 NOT NULL,
    CONSTRAINT pk_inventoryitem PRIMARY KEY (id)
);